In [1]:
import numpy as np

Numpy indexing and slicing of vectors

In [4]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[6]

np.int64(17)

In [6]:
arr[9]

np.int64(20)

In [12]:
arr_slice=arr[3::2]
arr_slice

array([14, 16, 18, 20])

numpy indexing and slicing of matrix

In [14]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [19]:
arr[5,4]

np.int64(30)

In [20]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [22]:
arr[3:5,3:5]

array([[19, 20],
       [24, 25]])

In [24]:
arr[0:,0:1]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21],
       [26]])

Boolean Indexing

In [26]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [27]:
bool_index=arr%2==0

In [28]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [29]:
arr= arr[bool_index]

In [30]:
arr

array([12, 14, 16, 18, 20])