In [1]:
import numpy as np

basic array creation

In [4]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
a=[1,2,3,4]
a

[1, 2, 3, 4]

In [9]:
a=[1,2,3,4.5]
a

[1, 2, 3, 4.5]

In [10]:
np.array(a)

array([1. , 2. , 3. , 4.5])

In [15]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array generation function

In [18]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr=np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
arr=np.ones((6,1))
arr

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [27]:
arr=np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [29]:
np.random.rand(5)

array([0.02076315, 0.61058265, 0.75785088, 0.07433473, 0.2558119 ])

In [35]:
np.random.randn(10)

array([-1.04328714,  0.24606063,  0.36356293,  1.0140844 , -2.32303737,
       -1.99791085,  1.5399805 ,  0.80045554, -0.1110579 ,  0.09886301])

In [38]:
np.random.randint(10,20,10)

array([19, 18, 13, 18, 11, 14, 16, 11, 19, 17], dtype=int32)

array attributes

In [40]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr.shape

(3, 3)

In [42]:
arr.size

9

In [43]:
arr.dtype

dtype('int64')

array methods

In [44]:
arr.min()

np.int64(1)

In [45]:
arr.max()

np.int64(9)

In [46]:
arr.sum()

np.int64(45)

In [48]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [49]:
arr.mean()

np.float64(5.0)

In [50]:
arr.std()

np.float64(2.581988897471611)

In [51]:
arr.argmin()

np.int64(0)

 reshaping and resizing

In [54]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [55]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])