In [1]:
import numpy as np


ARRAY OPERATIONS

ARTHMETIC OPRATIONS

In [3]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [4]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [5]:
a1-a2

array([-5, -5, -5, -5, -5])

In [6]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [7]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1//a2

array([0, 0, 0, 0, 0])

In [9]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

BROADCASTING

In [11]:
l=[10,20,30,40]
arr=np.array(l)

In [12]:
for i in l:
    print(i+10)
    #this in python

20
30
40
50


In [13]:
#but in  numpy it is easy this is broadcasting adding directly and easy 
arr+10

array([20, 30, 40, 50])

In [15]:
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
arr2+10


array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [17]:
arr2*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

DEEP AND SHALLOW COPY

In [18]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
slice=a[:5]
slice

array([1, 2, 3, 4, 5])

In [21]:
slice*10

array([10, 20, 30, 40, 50])

In [22]:
a
#if we did any changes in array slicesd part it wont effect the main array but in list it will effect the list

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
a[4:6]*10

array([50, 60])

In [25]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
a
b=a

In [27]:
b[0]=99

In [28]:
a


array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
#without changing actuall array
a
b=a.copy()
#now it wont effect the array a copy() function used here


In [31]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
b[0]=1
b


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
a


array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

MATRIX OPRATIONS

In [35]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])


In [36]:
A

array([[1, 2],
       [3, 4]])

In [37]:
B

array([[5, 6],
       [7, 8]])

In [38]:
A*B


array([[ 5, 12],
       [21, 32]])

In [39]:
#multiplying with actuall matrix formation
A@B

array([[19, 22],
       [43, 50]])

In [40]:
#one more method same as above
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [41]:
#transpose (reverse the array)
A.T

array([[1, 3],
       [2, 4]])

ADVANCED ARRAY OPERATIONS

In [42]:
A

array([[1, 2],
       [3, 4]])

In [43]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
#stacking of arrays we cannot do stack two matrix instead do two arrays or vectors

STACKING ARRAY

In [44]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [45]:
np.vstack((a,b))
#vstack is vertically stacking

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
#hstack is horizontally stacking
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
#column stack
np.column_stack((a,b))


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
#advance array manupulations only use vector we cannot use matrix

SPLITTING ARRAY

In [48]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
np.hsplit(c,2)
#we can only split in equal division of split

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [50]:
#for example here we fail
np.hsplit(c,3)

ValueError: array split does not result in an equal division

In [51]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [55]:
#vsplit
a=np.vsplit(c,4)
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [53]:
#vsplit
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [56]:
for i in a :
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
