In [1]:
import numpy as np

valid sudoku

In [2]:
import numpy as np

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [3]:
s.sum()

np.int64(405)

In [4]:
np.sum(s,axis=1)
#row sum axis=1

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [5]:
np.sum(s,axis=0)
#col sum axis=0

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [6]:
b=np.sum(s,axis=1)
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [12]:
for i in b:
    if i!=45:
        print("sudoku is not valid")
        break
else:
    print("for rows its valid")

for rows its valid


In [13]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [14]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [15]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [17]:
for i in range (0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3,j:j+3]
        print(n.sum())
#all 3/3 matrix sums in s

45
45
45
45
45
45
45
45
45


General Questions

In [48]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [49]:
#get the shape of the matrix


data.shape


(5, 3)

In [50]:
#find the average of the students.

np.mean(data[:,0])

np.float64(18.4)

In [51]:
#extract math marks of all students

data[:,1]


array([85, 92, 76, 65, 90])

In [52]:
#find the highest science marks
np.max(data[:,2])

np.int64(95)

In [53]:
#details of the students who scored more than 90 in math
data[:,1]

array([85, 92, 76, 65, 90])

In [54]:
data[data[:,1]>90]

array([[19, 92, 88]])

In [55]:
#increase all students math marks 5 for all students
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [56]:
#find how many students are younger than 19
len(data[data[:,0]>=19])

2

In [57]:
 #calculate the average marks in each subject
m=np.mean(data[:,1:],axis=0)
m

array([86.6, 83.2])

In [58]:
#get data if students whoscored at least 80 in both subjects
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [59]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [63]:
#replace all science marks<75 with 0
data[:,2][data[:,2]<75]=0

In [64]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])